[WIP] CI with NSX improvements
MissionCriticalCloud/bubble-toolkit pull request #217
Opened 2017-03-25 22:14 UTC by remibergsma

NSX improvements for our CI setup:
- add support for XenServer next to KVM
- find the right master controller and use that everywhere
- fix hardcoded NSX controller ip that would make zone2 setup fail
- split into two configs: minimal with single nodes and full blown cluster config (both KVM and XenServer)
- resolved instability, now builds reliably where it would fail 1:7 or so times

WIP: Still testing all the different options but starts to look good!

2017-03-25 22:36 UTC, remibergsma commented
This needs the latest version of Bubble Cookbook because the new hosts are added here: https://github.com/MissionCriticalCloud/bubble-cookbook/commit/057217b9acf1401adbee48fe8f0d2b582399a90a

2017-03-26 21:20 UTC, borisroman requested changes
Starts to look good! Few minor notes.

2017-03-26 21:20 UTC, borisroman commented on deploy/default/role/xenserver62.conf
> +postboot =
Newline

2017-03-26 21:20 UTC, borisroman commented on deploy/kvm_local_deploy.py
> +        pool = ThreadPool(10)
Virtual bubbles don't like this.

2017-03-26 21:20 UTC, borisroman commented on deploy/kvm_local_deploy.py
> +        pool = ThreadPool(10)
Virtual bubbles don't like this.

2017-03-26 21:20 UTC, borisroman commented on ci/ci-setup-infra.sh
> +  echo "set -x" > /tmp/nsx_cosmic.sh
`#!/usr/bin/env bash` 👍

2017-03-27 14:40 UTC, remibergsma commented
XenServer tests:

![image](https://cloud.githubusercontent.com/assets/1630096/24361916/873fcc60-130b-11e7-88bd-cbeca8ff362f.png)

![image](https://cloud.githubusercontent.com/assets/1630096/24361973/a8e1e330-130b-11e7-9a31-1328eb2d64d9.png)

![image](https://cloud.githubusercontent.com/assets/1630096/24362082/f957f0ac-130b-11e7-9b9f-a7e9de06a35f.png)

![image](https://cloud.githubusercontent.com/assets/1630096/24362129/1ad155b6-130c-11e7-9d53-cb000a6027f9.png)

2017-03-27 14:47 UTC, remibergsma commented on deploy/default/role/xenserver62.conf
> +postboot =
done

2017-03-27 15:23 UTC, remibergsma commented
KVM tests:

![image](https://cloud.githubusercontent.com/assets/1630096/24363032/daaf64ac-130e-11e7-8acb-987b9c45b060.png)

![image](https://cloud.githubusercontent.com/assets/1630096/24363715/ebaa2db2-1310-11e7-941f-f87385207cc5.png)

The other tests are still running...

2017-03-27 18:58 UTC, remibergsma commented
Rebased with latest master

2017-03-27 19:03 UTC, borisroman commented
@remibergsma Also remove this: https://github.com/MissionCriticalCloud/bubble-toolkit/blob/master/deploy/default/firstboot/configure_ovs.sh#L97

2017-03-27 19:32 UTC, remibergsma commented
The issue where no master could be found and the build would hang seems resolved with the retry:

Initially:
```
++ curl -L -sD - -k -b /tmp/nsx_cookie_14900.txt https://nsxcon4/ws.v1/control-cluster
++ egrep 'HTTP/1.1 200'
+ is_master=
+ '[' 1 -gt 0 ']'
+ say 'Controller nsxcon4 DOES NOT respond with 200 so this is NOT our master!'
+ echo '==> Controller nsxcon4 DOES NOT respond with 200 so this is NOT our master!'
==> Controller nsxcon4 DOES NOT respond with 200 so this is NOT our master!
+ say 'Output: '
+ echo '==> Output: '
==> Output:
```

In retry:

```
+ say 'Master not yet found, sleeping 10 sec and trying again..'
+ echo '==> Master not yet found, sleeping 10 sec and trying again..'
==> Master not yet found, sleeping 10 sec and trying again..
+ sleep 10
+ :
+ for i in 1 2 3 4 5 6 7 8 9
++ eval 'echo ${nsx_controller_node_ip1}'
+++ echo nsxcon4
+ '[' '!' -v nsxcon4 ']'
+ nsx_controller_node_ip=
+ eval 'nsx_controller_node_ip=${nsx_controller_node_ip1}'
++ nsx_controller_node_ip=nsxcon4
+ say 'Checking to see if nsxcon4 is master'
+ echo '==> Checking to see if nsxcon4 is master'
==> Checking to see if nsxcon4 is master
+ say 'Authenticating against NSX controller nsxcon4'
+ echo '==> Authenticating against NSX controller nsxcon4'
==> Authenticating against NSX controller nsxcon4
+ curl -L -k -c /tmp/nsx_cookie_14900.txt -X POST -d 'username=admin&password=admin' https://nsxcon4/ws.v1/login
Successful Authentication.

You successfully authenticated.  Use the cookie in this reply in future requests.
++ curl -L -sD - -k -b /tmp/nsx_cookie_14900.txt https://nsxcon4/ws.v1/control-cluster
++ egrep 'HTTP/1.1 200'
' is_master='HTTP/1.1 200 OK
+ '[' 0 -gt 0 ']'
+ say 'Controller nsxcon4 responds with 200 so this is our master!'
+ echo '==> Controller nsxcon4 responds with 200 so this is our master!'
==> Controller nsxcon4 responds with 200 so this is our master!
```

2017-03-28 07:35 UTC, remibergsma commented
The 2nd KVM setup works fine except for the nsxsvc4. Still investigating why that happens.

![image](https://cloud.githubusercontent.com/assets/1630096/24393811/dee98fd0-1399-11e7-9a33-ed2328149c42.png)

2017-03-28 07:41 UTC, remibergsma commented
It's something with the name, because with nsxsvc[23] it works fine ;-) 
![image](https://cloud.githubusercontent.com/assets/1630096/24394013/99c07d3c-139a-11e7-9304-16f7de11618b.png)

2017-04-01 11:56 UTC, borisroman approved these changes

2017-04-01 11:56 UTC, merged